---
- name: adapt puppet.conf
  command: "{{ puppet }} config set --section agent server {{ puppetagent_server }}"
- name: run puppet agent in no-operation mode and wait for the certificate
  command: "{{ puppet }} agent --onetime --no-daemonize --no-splay --waitforcert 30 --noop"
  when: puppetagent_waitforcert == true
- name: run puppet agent in no-operation mode
  command: "{{ puppet }} agent --onetime --no-daemonize --no-splay --noop"
  when: puppetagent_waitforcert == false
  ignore_errors: yes
