- name: get puppetlabs-release package
  get_url:
    url: "{{ remote_path }}"
    dest: "{{ local_path }}"
- name: remove puppet4 release package
  apt:
    name: puppetlabs-release-pc1
    state: absent
- name: install puppet5-release package
  apt:
    deb: "{{ local_path }}"
- name: install puppet-agent package
  apt:
    name: puppet-agent
    update_cache: yes
- name: append puppet executables to PATH for bash
  lineinfile:
    state: present
    line: 'export PATH=$PATH:/opt/puppetlabs/bin'
    dest: "{{ default_shell_config }}"
    insertafter: EOF
- name: append puppetserver ip to hosts file
  lineinfile:
    state: present
    line: "{{ puppetagent_server_ip }} {{ puppetagent_server }}"
    dest: '/etc/hosts'
    insertafter: EOF
  when: not puppetagent_server_ip == false
